feeds:
  - name: "Lenny's Podcast"
    url: "https://api.substack.com/feed/podcast/10845.rss"
    limit: 20
  - name: "BG2 Pod"
    url: "https://anchor.fm/s/f06c2370/podcast/rss"
    limit: 8
  - name: "Crucible Moments"
    url: "https://feeds.megaphone.fm/VMP5587961509"
    limit: 8
  - name: "Knowledge Project with Shane Paris"
    url: "https://feeds.megaphone.fm/FSMI7575968096"
    limit: 5
  - name: This week in ML
    url: "https://feeds.megaphone.fm/MLN2155636147"
    limit: 5
  - name: Last week in AI
    url: "https://www.lastweekinai.com/rss"
    limit: 5
  - name: Cognitive Revolution
    url: "https://feeds.megaphone.fm/RINTP3108857801"
    limit: 5
  - name: Huberman Lab
    url: "https://feeds.megaphone.fm/hubermanlab"
    limit: 5